import type { Profile, Review, Vault } from './types.ts';

const daysAgo = (n: number) => new Date(Date.now() - n * 86400000).toISOString();

export const DEMO_SELLERS: Profile[] = [
  {
    id: 'seller-nova',
    username: 'nova.notes',
    displayName: 'Nova Notes',
    bio: 'Building thinking systems in Obsidian since 2020. 40k+ students.',
    isSeller: true,
    payoutsEnabled: true,
    razorpayAccountId: 'acc_demo',
    createdAt: daysAgo(400),
  },
  {
    id: 'seller-kai',
    username: 'kai.builds',
    displayName: 'Kai Builds',
    bio: 'Engineer. I sell the vaults I actually use.',
    isSeller: true,
    payoutsEnabled: true,
    razorpayAccountId: 'acc_demo',
    createdAt: daysAgo(300),
  },
  {
    id: 'seller-mira',
    username: 'mira.phd',
    displayName: 'Mira, PhD',
    bio: 'Academic workflows, Zotero pipelines and literature reviews.',
    isSeller: true,
    payoutsEnabled: true,
    razorpayAccountId: 'acc_demo',
    createdAt: daysAgo(220),
  },
];

const seller = (id: string) => {
  const s = DEMO_SELLERS.find((p) => p.id === id)!;
  return { id: s.id, username: s.username, displayName: s.displayName, avatarUrl: s.avatarUrl };
};

export const DEMO_VAULTS: Vault[] = [
  {
    id: 'v-second-brain',
    sellerId: 'seller-nova',
    seller: seller('seller-nova'),
    title: 'Second Brain OS',
    tagline: 'A complete PARA + Zettelkasten system with dashboards that run themselves.',
    description:
      'Second Brain OS is the vault I have refined over four years. It combines PARA for projects and areas with a Zettelkasten for permanent notes, wired together with Dataview dashboards.\n\nWhat you get:\n• Home dashboard with today, active projects, and inbox counts\n• 24 templates (project, area, person, meeting, book, weekly review...)\n• Automated MOCs that update as you write\n• A 40-minute onboarding video and a written setup guide\n\nWorks on desktop and mobile. Requires Dataview, Templater and Periodic Notes (all free).',
    category: 'pkm',
    tags: ['para', 'zettelkasten', 'dataview', 'dashboard'],
    priceCents: 249900,
    currency: 'INR',
    screenshots: [],
    plugins: ['Dataview', 'Templater', 'Periodic Notes', 'Calendar'],
    noteCount: 148,
    sizeBytes: 4_300_000,
    version: '3.2',
    status: 'published',
    downloads: 4210,
    ratingAvg: 4.8,
    ratingCount: 312,
    featured: true,
    createdAt: daysAgo(380),
    updatedAt: daysAgo(12),
  },
  {
    id: 'v-student-kit',
    sellerId: 'seller-mira',
    seller: seller('seller-mira'),
    title: 'University Starter Kit',
    tagline: 'Courses, lectures, assignments and exam prep, organised for the whole degree.',
    description:
      'Built for undergrads and grad students. One folder per semester, a course template that generates lecture and assignment notes, and an exam countdown dashboard.\n\nIncludes flashcard-ready note formats compatible with the Spaced Repetition plugin.',
    category: 'students',
    tags: ['university', 'lectures', 'spaced-repetition', 'exams'],
    priceCents: 0,
    currency: 'INR',
    screenshots: [],
    plugins: ['Dataview', 'Spaced Repetition', 'Calendar'],
    noteCount: 62,
    sizeBytes: 1_100_000,
    version: '2.0',
    status: 'published',
    downloads: 18930,
    ratingAvg: 4.6,
    ratingCount: 1204,
    featured: true,
    createdAt: daysAgo(260),
    updatedAt: daysAgo(40),
  },
  {
    id: 'v-dev-brain',
    sellerId: 'seller-kai',
    seller: seller('seller-kai'),
    title: 'Engineering Knowledge Base',
    tagline: 'Snippets, ADRs, runbooks and interview prep in one searchable vault.',
    description:
      'The vault I use as a staff engineer. Architecture Decision Record templates, incident runbooks, a snippet library with syntax-highlighted code blocks, and a system-design study track.\n\nComes with a CLI script that imports your GitHub stars as notes.',
    category: 'developers',
    tags: ['engineering', 'adr', 'snippets', 'system-design'],
    priceCents: 149900,
    currency: 'INR',
    screenshots: [],
    plugins: ['Dataview', 'Templater', 'Code Block Copy', 'Excalidraw'],
    noteCount: 210,
    sizeBytes: 7_800_000,
    version: '1.6',
    status: 'published',
    downloads: 2380,
    ratingAvg: 4.9,
    ratingCount: 188,
    featured: true,
    createdAt: daysAgo(200),
    updatedAt: daysAgo(5),
  },
  {
    id: 'v-research',
    sellerId: 'seller-mira',
    seller: seller('seller-mira'),
    title: 'Literature Review Machine',
    tagline: 'Zotero to Obsidian pipeline with paper templates and a synthesis matrix.',
    description:
      'Turn a pile of PDFs into a structured literature review. Paper notes are generated from Zotero with one hotkey, tagged by theme, and rolled up into a synthesis matrix you can paste into your thesis.',
    category: 'research',
    tags: ['zotero', 'academic', 'literature-review', 'thesis'],
    priceCents: 199900,
    currency: 'INR',
    screenshots: [],
    plugins: ['Zotero Integration', 'Dataview', 'Templater', 'Pandoc'],
    noteCount: 54,
    sizeBytes: 2_200_000,
    version: '1.3',
    status: 'published',
    downloads: 1560,
    ratingAvg: 4.7,
    ratingCount: 97,
    featured: false,
    createdAt: daysAgo(150),
    updatedAt: daysAgo(30),
  },
  {
    id: 'v-novelist',
    sellerId: 'seller-nova',
    seller: seller('seller-nova'),
    title: "Novelist's Workbench",
    tagline: 'Characters, scenes, timelines and a manuscript compiler for fiction writers.',
    description:
      'Plan and draft an entire novel inside Obsidian. Character and location sheets, a scene board with Kanban, a timeline view, and a Longform-ready manuscript structure that exports to DOCX.',
    category: 'writing',
    tags: ['fiction', 'longform', 'kanban', 'worldbuilding'],
    priceCents: 129900,
    currency: 'INR',
    screenshots: [],
    plugins: ['Longform', 'Kanban', 'Dataview'],
    noteCount: 88,
    sizeBytes: 1_900_000,
    version: '2.1',
    status: 'published',
    downloads: 3120,
    ratingAvg: 4.5,
    ratingCount: 241,
    featured: false,
    createdAt: daysAgo(310),
    updatedAt: daysAgo(70),
  },
  {
    id: 'v-daily',
    sellerId: 'seller-kai',
    seller: seller('seller-kai'),
    title: 'Minimal Daily Journal',
    tagline: 'A calm daily, weekly and monthly review system. No plugins required.',
    description:
      'Three templates, one folder, zero plugins. Morning pages, evening reflection, and weekly reviews that link to each other automatically with core Obsidian features only.',
    category: 'life',
    tags: ['journal', 'habits', 'minimal', 'no-plugins'],
    priceCents: 0,
    currency: 'INR',
    screenshots: [],
    plugins: [],
    noteCount: 12,
    sizeBytes: 90_000,
    version: '1.0',
    status: 'published',
    downloads: 26400,
    ratingAvg: 4.4,
    ratingCount: 1890,
    featured: false,
    createdAt: daysAgo(420),
    updatedAt: daysAgo(200),
  },
  {
    id: 'v-founder',
    sellerId: 'seller-nova',
    seller: seller('seller-nova'),
    title: 'Founder Command Center',
    tagline: 'OKRs, investor CRM, meeting notes and a weekly metrics dashboard.',
    description:
      'Run a startup from one vault. OKR tracker, investor and customer CRM with Dataview tables, board-meeting templates and a metrics page that pulls from your weekly updates.',
    category: 'business',
    tags: ['startup', 'okr', 'crm', 'meetings'],
    priceCents: 399900,
    currency: 'INR',
    screenshots: [],
    plugins: ['Dataview', 'Templater', 'Tasks'],
    noteCount: 76,
    sizeBytes: 3_100_000,
    version: '1.1',
    status: 'published',
    downloads: 640,
    ratingAvg: 4.9,
    ratingCount: 58,
    featured: false,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(9),
  },
  {
    id: 'v-templates',
    sellerId: 'seller-kai',
    seller: seller('seller-kai'),
    title: '100 Templater Templates',
    tagline: 'Drop-in templates for meetings, people, books, recipes, trips and more.',
    description:
      'A hundred battle-tested Templater templates with sensible front matter and Dataview-friendly fields. Import the folder and start using them in minutes.',
    category: 'templates',
    tags: ['templater', 'templates', 'frontmatter'],
    priceCents: 79900,
    currency: 'INR',
    screenshots: [],
    plugins: ['Templater'],
    noteCount: 100,
    sizeBytes: 400_000,
    version: '4.0',
    status: 'published',
    downloads: 5210,
    ratingAvg: 4.6,
    ratingCount: 402,
    featured: false,
    createdAt: daysAgo(500),
    updatedAt: daysAgo(15),
  },
];

export const DEMO_REVIEWS: Review[] = [
  {
    id: 'r1',
    vaultId: 'v-second-brain',
    userId: 'u-1',
    rating: 5,
    body: 'Replaced three apps for me. The onboarding video alone is worth the price.',
    createdAt: daysAgo(20),
    author: { id: 'u-1', username: 'devon', displayName: 'Devon' },
  },
  {
    id: 'r2',
    vaultId: 'v-second-brain',
    userId: 'u-2',
    rating: 4,
    body: 'Excellent structure. Took me a weekend to migrate but the dashboards are great.',
    createdAt: daysAgo(45),
    author: { id: 'u-2', username: 'sam.k', displayName: 'Sam K.' },
  },
  {
    id: 'r3',
    vaultId: 'v-student-kit',
    userId: 'u-3',
    rating: 5,
    body: 'Used it through my whole final year. Exam dashboard is a lifesaver.',
    createdAt: daysAgo(60),
    author: { id: 'u-3', username: 'priya', displayName: 'Priya' },
  },
  {
    id: 'r4',
    vaultId: 'v-dev-brain',
    userId: 'u-4',
    rating: 5,
    body: 'ADR templates are exactly what my team needed. Imported into our shared vault.',
    createdAt: daysAgo(8),
    author: { id: 'u-4', username: 'lin', displayName: 'Lin' },
  },
];
